### ISSUE TITLE
Task 6: Mobile download fail on certification

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#35]
![image](https://github.com/user-attachments/assets/a45034ff-d63f-442d-ae8d-9ac5c35c7fe2)

Solution: the problem is current code is building one frame in big screen where there is certificate image in background and over that image there is text . which previous contributor has aligned manually so when we click on download so that frame is getting download as it is . which he have handled upto screen width of 1080px .after that the text and image is not handled . +the frame display gets none after 1080px screen so thats why when we try to download certificate its give 0B image (coruptt image) because frame doesnt exist in that device .

https://gssoc.girlscript.tech/verify_cert

**Comment by shreyash3087** [comment]
@sanjay-kv i had a solution for this which i mentioned in #15 simply to put the certificate frame out of the screen instead of making it's display none for smaller devices,i have tested it and it works fine, can i fix it?


https://github.com/user-attachments/assets/6924956c-d4a0-42ad-86d4-00f834bd6331

**Comment by sanjay-kv** [comment]
yes its doable you can raise the PR
